// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1IbxED_3ZP6WuHhcC7uTZVFVEbAI1VGo',
    appId: '1:256309139379:web:e39b25fe23f121183c9dc6',
    messagingSenderId: '256309139379',
    projectId: 'ventimetriappclienti',
    authDomain: 'ventimetriappclienti.firebaseapp.com',
    storageBucket: 'ventimetriappclienti.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyDwIsTTOEndZm4eP1yV8u0g9N_wIfSW8',
    appId: '1:256309139379:android:bdb8b97447571e063c9dc6',
    messagingSenderId: '256309139379',
    projectId: 'ventimetriappclienti',
    storageBucket: 'ventimetriappclienti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdzyu7IOMBjUHA5OBTcMXl-mPI-Ty8Zds',
    appId: '1:256309139379:ios:b9bd55168b436bde3c9dc6',
    messagingSenderId: '256309139379',
    projectId: 'ventimetriappclienti',
    storageBucket: 'ventimetriappclienti.appspot.com',
    iosBundleId: 'com.ventimetriquadri.appclienti.ventimetriappclienti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdzyu7IOMBjUHA5OBTcMXl-mPI-Ty8Zds',
    appId: '1:256309139379:ios:d30a0470fbb430a23c9dc6',
    messagingSenderId: '256309139379',
    projectId: 'ventimetriappclienti',
    storageBucket: 'ventimetriappclienti.appspot.com',
    iosBundleId: 'com.ventimetriquadri.appclienti.ventimetriappclienti.RunnerTests',
  );
}
